- name: Install NGINX-conf
  become: true
  hosts: all
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install NGINX
      apt:
        name: nginx
        state: present

    - name: Enable NGINX service
      systemd:
        name: nginx
        enabled: yes
    - name: Setup nginx conf
      template:
        src=nginx.conf.tpl
        dest=/etc/nginx/sites-enabled/django.conf
    - name: restart nginx
      service: name=nginx state=restarted